### ISSUE TITLE
n9e-agent make error

### ISSUE THREAD

**Issue by grexkin** [n9e/n9e-agentd#2]
make
mkdir -p build
GO111MODULE=on CGO_ENABLED=1 \
go build -ldflags '-w -s -X github.com/n9e/n9e-agentd/pkg/options.Revision=80cdc69 -X github.com/n9e/n9e-agentd/pkg/options.Branch=master -X github.com/n9e/n9e-agentd/pkg/options.Version=pre-release -X github.com/n9e/n9e-agentd/pkg/options.BuildDate=2021-07-14-11:30:00 -X github.com/n9e/n9e-agentd/pkg/options.BuildTimeUnix=1626233400 -X github.com/n9e/n9e-agentd/pkg/options.Builder=root@k8s-master -X github.com/n9e/n9e-agentd/pkg/options.LogBuildInfoAtStartup=true' \
-o build/n9e-agentd ./cmd/agentd && \
build/n9e-agentd version
# github.com/n9e/n9e-agentd/pkg/util/db
pkg/util/db/query.go:11:14: undefined: CustomQuery
pkg/util/db/query.go:35:18: undefined: CustomQuery
make: *** [build/n9e-agentd] Error 2

**Comment by hagic-hhj** [comment]
me too

**Comment by yubo** [comment]
fixed 73a4968
