### ISSUE TITLE
make pkg 编译失败

### ISSUE THREAD

**Issue by Alex-ai** [n9e/n9e-agentd#3]
系统：CentOS Linux release 8.2.2004 (Core)
编译错误：
make pkg
VERSION=5.0.0 RELEASE=rc5 ./scripts/pkg.sh
make[1]: 进入目录“/opt/mygo/src/n9e-agentd”
GO111MODULE=on CGO_ENABLED=1 \
go build -ldflags '-w -s -X github.com/n9e/n9e-agentd/pkg/options.Revision=58e9417 -X github.com/n9e/n9e-agentd/pkg/options.Branch=main -X github.com/n9e/n9e-agentd/pkg/options.Version=pre-release -X github.com/n9e/n9e-agentd/pkg/options.BuildDate=2021-07-22-22:38:33 -X github.com/n9e/n9e-agentd/pkg/options.BuildTimeUnix=1626964713 -X github.com/n9e/n9e-agentd/pkg/options.Builder=root@localhost.localdomain -X github.com/n9e/n9e-agentd/pkg/options.LogBuildInfoAtStartup=true' \
-o build/n9e-agentd ./cmd/agentd && \
build/n9e-agentd version
**go: github.com/yubo/golib@v0.0.0-20210721045300-a4de815531cb: parsing /home/odin/steveyubo/gopath/src/github.com/yubo/golib/go.mod: open /home/odin/steveyubo/gopath/src/github.com/yubo/golib/go.mod: no such file or directory**

**Comment by yubo** [comment]
try:
git fetch
git checkout v5.0.0-rc6
