### ISSUE TITLE
make pkg 编译错误

### ISSUE THREAD

**Issue by Alex-ai** [n9e/n9e-agentd#4]
VERSION=5.0.0 RELEASE=rc5 ./scripts/pkg.sh
make[1]: 进入目录“/opt/mygo/src/n9e-agentd”
GO111MODULE=on CGO_ENABLED=1 \
go build -ldflags '-w -s -X github.com/n9e/n9e-agentd/pkg/options.Revision=58e9417 -X github.com/n9e/n9e-agentd/pkg/options.Branch=main -X github.com/n9e/n9e-agentd/pkg/options.Version=pre-release -X github.com/n9e/n9e-agentd/pkg/options.BuildDate=2021-07-22-23:12:55 -X github.com/n9e/n9e-agentd/pkg/options.BuildTimeUnix=1626966775 -X github.com/n9e/n9e-agentd/pkg/options.Builder=root@localhost.localdomain -X github.com/n9e/n9e-agentd/pkg/options.LogBuildInfoAtStartup=true' \
-o build/n9e-agentd ./cmd/agentd && \
build/n9e-agentd version
 github.com/yubo/golib/util
In file included from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/stdlib.h:25,
                 from _cgo_export.c:3:
/usr/include/features.h:184:3: 警告：#warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
 warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^~~~~~~
 github.com/yubo/golib/util
In file included from /usr/include/sys/types.h:25,
                 from /home/odin/steveyubo/gopath/src/github.com/yubo/golib/util/getugroups_unix.go:8:
/usr/include/features.h:184:3: 警告：#warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
  warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^~~~~~~
_panic: unsupported type uint16

goroutine 1 [running]:
github.com/yubo/golib/configer.addFlag(0xc000124500, 0xc00011fd80, 0x2, 0x2, 0x1c35500, 0x18092c0, 0x1, 0x2)
        /home/odin/steveyubo/gopath/src/github.com/yubo/golib/configer/flag.go:204 +0x1d5c
github.com/yubo/golib/configer.addFlag(0xc000124500, 0xc00012d200, 0x1, 0x1, 0x1c35500, 0x18f5bc0, 0xc00012d200, 0x1)
        /home/odin/steveyubo/gopath/src/github.com/yubo/golib/configer/flag.go:168 +0x1956
github.com/yubo/golib/configer.AddFlags(0xc000124500, 0x18f9d6b, 0x5, 0x187a0a0, 0xc000176000, 0xc00012d1f0, 0x0)
        /home/odin/steveyubo/gopath/src/github.com/yubo/golib/configer/flag.go:123 +0x23f
github.com/yubo/golib/proc.RegisterFlags(0x18f9d6b, 0x5, 0x190f665, 0xd, 0x187a0a0, 0xc000176000)
        /home/odin/steveyubo/gopath/src/github.com/yubo/golib/proc/cmd.go:90 +0xdd
github.com/n9e/n9e-agentd/pkg/config.AddFlags()
        /opt/mygo/src/n9e-agentd/pkg/config/config.go:68 +0x75
github.com/n9e/n9e-agentd/pkg/agent.init.0()
        /opt/mygo/src/n9e-agentd/pkg/agent/agent.go:276 +0x4a
make[1]: *** [Makefile:42：build/n9e-agentd] 错误 2
make[1]: 离开目录“/opt/mygo/src/n9e-agentd”_

**Comment by yubo** [comment]
What is the OS and CPU Arch type used?
