### ISSUE TITLE
关于V5版本script插件运行超时时间问题

### ISSUE THREAD

**Issue by FE-wangjb** [n9e/n9e-agentd#6]
在V5运行插件的过程中发现，有的插件指标未上报，查看日志，有如下信息：
n9e-agentd[25805]: W0819 12:09:43.988682   25805 script.go:194] /opt/n9e/server/plugin/hwcloud/60_hwrds_tps.py run err signal: killed
       手工执行脚本完全没有问题，后来查询script.go源码发现，defaultTimeout = 5，用shell脚本sleep测试，sleep超过5秒会报同样错误，小于5秒则正常。尝试改了下./conf.d/script.d/conf.yaml，发现好像也没有生效，因本人go语言不熟，所以无法看懂这个处理机制到底是什么样的，烦请开发者帮忙解答，感谢！

**Comment by yubo** [comment]
脚本调用需要5秒内返回。脚本的调用应该是无状态，没有上下文的。
