### ISSUE TITLE
关于windows下agent不能正常运行的问题

### ISSUE THREAD

**Issue by Puma000009** [n9e/n9e-agentd#7]
下载二进制包n9e-agentd-5.0.0-rc8.windows.amd64.tar.gz
1.cmd执行命令：.\n9e-agentd.exe -f f:\agent-win\etc\agentd.yaml
提示错误：[关于token的]
```
Getting sidstring from current user Error: authentication.tokenAuthFile.init() err: error writing authentication token file on fs: open ./etc/auth_token: The system cannot find the path specified.
E0823 15:24:49.252929    6712 agentd.go:14] authentication.tokenAuthFile.init()err: error writing authentication token file on fs: open ./etc/auth_token: The system cannot find the path specified.
```
而etc/下根本没有tokenAuth文件。

**Comment by yubo** [comment]
cd f:\agent-win 
.\bin\n9e-agentd.exe -f .\etc\agentd.yaml

**Comment by Puma000009** [comment]
> cd f:\agent-win
> .\bin\n9e-agentd.exe -f .\etc\agentd.yaml

我的操作跟你的也没有区别呀,.
而且我的问题是没有auth_token,请问下这个auth_token怎么生成？

**Comment by Puma000009** [comment]
搞定了.
1命令没问题;
2.需要在可执行文件所在路径创建个文件加etc,用于存放自动生成的token.---我的问题就在于此.

另:1此win版本其实和我从linux版直接改过来的一样,原则上不是为了win开发的,很多配置都是linux习惯.因此出现问题,
    2此win版本没能做成service，着实不算win版本。而且很多监控内容都不能用；

**Comment by Puma000009** [comment]
搞定了.
1命令没问题;
2.需要在可执行文件所在路径创建个文件加etc,用于存放自动生成的token.---我的问题就在于此.

另:1此win版本其实和我从linux版直接改过来的一样,原则上不是为了win开发的,很多配置都是linux习惯.因此出现问题,
    2此win版本没能做成service，着实不算win版本。而且很多监控内容都不能用；
