### ISSUE TITLE
agent采集的system_mem_used_percent与实际的机器上的内存使用率不符

### ISSUE THREAD

**Issue by lizhaoyang1990** [n9e/n9e-agentd#8]
在对十几台机器巡检过程中发现有一台机器的通过agent采集的system_mem_used_percent和机器实际使用率不一致。及其异常
![image](https://user-images.githubusercontent.com/18639238/131599167-67f60d04-19ce-40f8-b622-0a559f40e303.png)

![image](https://user-images.githubusercontent.com/18639238/131599080-69d7b98a-e6e8-41d4-8abd-4d496284fbd2.png)
而实际机器上的used内存是基本恒定的
124g 总内存256g

**Comment by yubo** [comment]
I haven't encountered it yet. I suspect that the two machines use the same ident. Let's see if other people encounter the same situation
