### ISSUE TITLE
need centos 6 glibc-2.12 agent. 

### ISSUE THREAD

**Issue by lichengshuang** [n9e/n9e-agentd#9]
当在centos6 自己编译或者在centos7 环境用docker 编译报错 
在墙外编译新包  也是报  go: code.cloudfoundry.org/bbs@v0.0.0-20200403215808-d7bc971db0db: Get 
能否 你们编译出一个 依赖glibc-2.12 的包出来。 

bash -x build-glib212.sh
+++ dirname build-glib212.sh
++ cd ./
++ pwd
+ CWD=/export/github/n9e-agentd/scripts
+ cd /export/github/n9e-agentd/scripts/..
+ docker run --rm -w /src -v /export/github/n9e-agentd:/src -e RELEASE_EXTRA=glib212 -e PATH=/go/bin:/usr/bin:/bin -e GOROOT=/go --name golang-builder --hostname glib212-builder -it ybbbbasdf/centos:glib2.12 make pkg
VERSION=5.0.0 RELEASE=rc8 ./scripts/pkg.sh
make[1]: Entering directory `/src'
unset GOFLAGS && \
        GO111MODULE=on CGO_ENABLED=1 \
        go build -ldflags '-w -s -X github.com/n9e/n9e-agentd/pkg/options.Revision=9ab707b -X github.com/n9e/n9e-agentd/pkg/options.Branch=main -X github.com/n9e/n9e-agentd/pkg/options.Version=v5.0.0-rc8 -X github.com/n9e/n9e-agentd/pkg/options.BuildDate=2021-09-05-07:16:03 -X github.com/n9e/n9e-agentd/pkg/options.BuildTimeUnix=1630826163 -X github.com/n9e/n9e-agentd/pkg/options.Builder=root@glib212-builder -X github.com/n9e/n9e-agentd/pkg/options.LogBuildInfoAtStartup=true' \
        -o build/n9e-agentd ./cmd/agentd && \
        build/n9e-agentd version

go: code.cloudfoundry.org/bbs@v0.0.0-20200403215808-d7bc971db0db: Get "https://proxy.golang.org/code.cloudfoundry.org/bbs/@v/v0.0.0-20200403215808-d7bc971db0db.mod": dial tcp 172.217.160.81:443: i/o timeout
make[1]: *** [build/n9e-agentd] Error 1
make[1]: Leaving directory `/src'
make: *** [pkg] Error 1

**Comment by FE-wangjb** [comment]
我这边有几台CentOS6.8也因此搁置了，现网、老机器、老业务，不敢随便升级

**Comment by lichengshuang** [comment]
> 我这边有几台CentOS6.8也因此搁置了，现网、老机器、老业务，不敢随便升级
centos 6.10 , 通过升级glibc2.14 成功了一台， 另外2台 能执行， 但是加载配置文件出现莫名其妙的错误。 明天再看看 能不能。 对于这种客户端  应该 就搞一个不依赖任何库文件的 二进制， 不然 比python不同版本还难处理。 尤其glibc的东西。 搞不好 系统命令都用不了了。

**Comment by yubo** [comment]
https://github.com/n9e/n9e-agentd/blob/main/docs/centos6.md
